"""SBOM router: exposes application and per-engagement SBOMs."""
from __future__ import annotations

import json
import uuid

import structlog
from fastapi import APIRouter, Query
from fastapi.responses import Response
from sqlalchemy import select

from app.core.deps import CurrentUser, DB
from app.core.permissions import Role, require_role
from app.models.engagement import Engagement

logger = structlog.get_logger(__name__)
router = APIRouter(prefix="/sbom", tags=["sbom"])


@router.get("")
async def get_application_sbom(
    current_user: CurrentUser,
    _db: DB,
    format: str = Query(default="cyclonedx", pattern="^(cyclonedx|spdx)$"),
):
    """Return the application SBOM (all installed Python packages).

    - ``format=cyclonedx`` (default): CycloneDX 1.5 JSON
    - ``format=spdx``: SPDX 2.3 JSON
    """
    require_role(current_user.role, Role.viewer)

    from app.services.sbom import build_cyclonedx, build_spdx

    if format == "spdx":
        sbom = build_spdx()
        filename = "drift-sbom.spdx.json"
    else:
        sbom = build_cyclonedx()
        filename = "drift-sbom.cdx.json"

    return Response(
        content=json.dumps(sbom, indent=2).encode("utf-8"),
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/engagements/{engagement_id}")
async def get_engagement_sbom(
    engagement_id: uuid.UUID,
    current_user: CurrentUser,
    db: DB,
    format: str = Query(default="cyclonedx", pattern="^(cyclonedx|spdx)$"),
):
    """Return the SBOM for a specific engagement (scoped to that engagement's context).

    This returns the same application SBOM with the engagement ID embedded
    in the metadata. Per-run SBOMs (generated by Syft on the tools container
    during a scan) are stored as MinIO artifacts at
    ``artifacts/{engagement_id}/{run_id}/sbom.cdx.json`` and served separately.
    """
    require_role(current_user.role, Role.viewer)

    # Verify engagement exists
    engagement = await db.get(Engagement, engagement_id)
    if not engagement:
        from fastapi import HTTPException, status
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"type": "about:blank", "title": "Not Found",
                    "status": 404, "detail": "Engagement not found"},
        )

    from app.services.sbom import build_cyclonedx, build_spdx

    if format == "spdx":
        sbom = build_spdx(engagement_id=str(engagement_id))
        filename = f"drift-sbom-{engagement_id}.spdx.json"
    else:
        sbom = build_cyclonedx(engagement_id=str(engagement_id))
        filename = f"drift-sbom-{engagement_id}.cdx.json"

    return Response(
        content=json.dumps(sbom, indent=2).encode("utf-8"),
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/summary")
async def get_sbom_summary(
    current_user: CurrentUser,
    _db: DB,
):
    """Return a summary of the application SBOM (component count, format, version)."""
    require_role(current_user.role, Role.viewer)

    from app.services.sbom import _get_installed_packages, _APP_VERSION
    packages = _get_installed_packages()

    return {
        "app_version": _APP_VERSION,
        "bom_format": "CycloneDX",
        "spec_version": "1.5",
        "component_count": len(packages),
        "endpoints": {
            "cyclonedx": "/api/sbom?format=cyclonedx",
            "spdx": "/api/sbom?format=spdx",
        },
    }
