{{- if .Values.persistence.audit.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drift.fullname" . }}-audit
  labels:
    {{- include "drift.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.persistence.audit.accessMode }}
  {{- if .Values.persistence.audit.storageClass }}
  storageClassName: {{ .Values.persistence.audit.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.audit.size }}
{{- end }}
