#!/usr/bin/env bash
# Drift — Debian server setup + first-run
# Run as root: bash scripts/setup.sh
set -euo pipefail

BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

info()  { echo -e "${GREEN}[+]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[!]${RESET} $*"; }
fatal() { echo -e "${RED}[✗]${RESET} $*"; exit 1; }

[[ $EUID -eq 0 ]] || fatal "Run as root (sudo bash scripts/setup.sh)"

# ── Deployment mode ────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Deployment mode:${RESET}"
echo "  1) Standalone   — Drift nginx handles TLS directly (ports 80 + 443)"
echo "  2) Behind proxy — Existing reverse proxy handles TLS; Drift listens on HTTP"
echo ""
read -rp "Select [1/2, default=1]: " DEPLOY_MODE
DEPLOY_MODE=${DEPLOY_MODE:-1}

if [[ "$DEPLOY_MODE" != "1" && "$DEPLOY_MODE" != "2" ]]; then
    fatal "Invalid selection. Choose 1 or 2."
fi

PROXY_PORT=8080
if [[ "$DEPLOY_MODE" == "2" ]]; then
    read -rp "Port for upstream proxy to forward to [default=8080]: " _PORT
    PROXY_PORT=${_PORT:-8080}
    info "Behind-proxy mode: Drift will listen on HTTP port ${PROXY_PORT}."
    warn "Configure your reverse proxy to forward to this host:${PROXY_PORT}."
    warn "Your proxy must set X-Forwarded-For and X-Forwarded-Proto headers."
else
    info "Standalone mode: Drift will bind ports 80 and 443."
fi
echo ""

# ── System packages ────────────────────────────────────────────────────────────
info "Updating system packages..."
apt-get update -q
apt-get install -y --no-install-recommends \
    curl gnupg ca-certificates lsb-release \
    ufw fail2ban \
    python3 python3-venv python3-pip \
    libmagic1 libpq-dev

# ── Docker ─────────────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
fi

if ! command -v docker &>/dev/null; then
    fatal "Docker install failed"
fi
info "Docker: $(docker --version)"

# ── Firewall ───────────────────────────────────────────────────────────────────
info "Configuring UFW firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh

if [[ "$DEPLOY_MODE" == "1" ]]; then
    ufw allow 80/tcp
    ufw allow 443/tcp
else
    ufw allow "${PROXY_PORT}/tcp"
    info "UFW: opened port ${PROXY_PORT}/tcp for reverse proxy forwarding."
    warn "Ensure your reverse proxy server's IP is the only source reaching port ${PROXY_PORT}."
    warn "Consider: ufw allow from <proxy-ip> to any port ${PROXY_PORT}"
fi

ufw --force enable
info "Firewall active."

# ── fail2ban ───────────────────────────────────────────────────────────────────
info "Configuring fail2ban..."
cat > /etc/fail2ban/jail.local <<'EOF'
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 5

[sshd]
enabled = true
port    = ssh

[nginx-http-auth]
enabled = true
EOF
systemctl enable fail2ban
systemctl restart fail2ban

# ── App directories ────────────────────────────────────────────────────────────
info "Creating app directories..."
mkdir -p /var/drift/uploads /var/drift/logs
useradd -r -s /bin/false drift 2>/dev/null || true
chown -R drift:drift /var/drift

# ── Environment ────────────────────────────────────────────────────────────────
ROOT_DIR="$(dirname "$0")/.."
BACKEND_DIR="${ROOT_DIR}/backend"

if [[ ! -f "$BACKEND_DIR/.env" ]]; then
    info "Generating .env from template..."
    cp "$BACKEND_DIR/.env.example" "$BACKEND_DIR/.env"

    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(64))")
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    REDIS_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    VAULT_KEY=$(python3 -c "import os, base64; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")

    sed -i "s|CHANGE_ME_64_BYTE_HEX_SECRET|$JWT_SECRET|" "$BACKEND_DIR/.env"
    sed -i "s|CHANGE_ME_32_BYTE_HEX_SECRET|$SECRET_KEY|" "$BACKEND_DIR/.env"
    sed -i "s|CHANGE_ME_FERNET_KEY|$VAULT_KEY|" "$BACKEND_DIR/.env"

    cat > "${ROOT_DIR}/.env" <<ENVEOF
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
ENVEOF

    warn ".env generated with auto-generated secrets."
    warn "Edit backend/.env to configure SMTP, allowed origins, and domain."
else
    info ".env already exists — skipping generation."
fi

# ── docker-compose.override.yml ────────────────────────────────────────────────
info "Writing docker-compose.override.yml..."

if [[ "$DEPLOY_MODE" == "1" ]]; then
    # Standalone: nginx owns TLS on 80+443
    cat > "${ROOT_DIR}/docker-compose.override.yml" <<OVERRIDE
# Generated by scripts/setup.sh — standalone TLS mode
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/drift.conf:/etc/nginx/conf.d/drift.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - frontend:/var/www/drift:ro
OVERRIDE
else
    # Behind proxy: HTTP only on configurable port
    cat > "${ROOT_DIR}/docker-compose.override.yml" <<OVERRIDE
# Generated by scripts/setup.sh — behind-proxy HTTP mode
services:
  nginx:
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./nginx/drift-behind-proxy.conf:/etc/nginx/conf.d/drift.conf:ro
      - frontend:/var/www/drift:ro
OVERRIDE
fi

info "docker-compose.override.yml written."

# ── SSL (standalone mode only) ─────────────────────────────────────────────────
if [[ "$DEPLOY_MODE" == "1" ]]; then
    NGINX_SSL="${ROOT_DIR}/nginx/ssl"
    mkdir -p "$NGINX_SSL"
    if [[ ! -f "$NGINX_SSL/fullchain.pem" ]]; then
        warn "Generating self-signed SSL certificate (replace with real cert for production)..."
        openssl req -x509 -newkey rsa:4096 -keyout "$NGINX_SSL/privkey.pem" \
            -out "$NGINX_SSL/fullchain.pem" -days 365 -nodes \
            -subj "/CN=drift.local/O=Drift/C=US" 2>/dev/null
        info "Self-signed cert at nginx/ssl/. Replace with Let's Encrypt for production."
    else
        info "SSL cert already exists — skipping generation."
    fi
fi

# ── Build & start ──────────────────────────────────────────────────────────────
info "Building Docker images..."
cd "${ROOT_DIR}"

info "Copying frontend to nginx volume..."
docker volume create drift_frontend 2>/dev/null || true
docker run --rm -v "$(pwd):/src" -v "drift_frontend:/dst" alpine \
    sh -c "cp /src/index.html /dst/index.html"

docker compose build

info "Running database migrations..."
docker compose up -d db redis
sleep 5

docker compose run --rm api alembic upgrade head

# Create initial admin user
info "Creating initial admin user..."
ADMIN_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")
docker compose run --rm api python3 -c "
import asyncio
from app.database import AsyncSessionLocal
from app.models.user import User
from app.core.security import hash_password

async def create_admin():
    async with AsyncSessionLocal() as db:
        u = User(
            username='admin',
            email='admin@drift.local',
            full_name='Admin',
            role='admin',
            hashed_password=hash_password('$ADMIN_PASS'),
            is_active=True,
        )
        db.add(u)
        await db.commit()
        print('Admin user created.')

asyncio.run(create_admin())
" 2>/dev/null || warn "Admin user may already exist."

info "Starting Drift..."
docker compose up -d

echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD} Drift is running!${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

if [[ "$DEPLOY_MODE" == "1" ]]; then
    echo "  URL:      https://$(hostname -I | awk '{print $1}')"
else
    echo "  Internal: http://$(hostname -I | awk '{print $1}'):${PROXY_PORT}"
    echo "  Point your reverse proxy at the above address."
fi

echo "  Username: admin"
echo "  Password: ${ADMIN_PASS}"
echo ""
warn "Save that password — it won't be shown again."

if [[ "$DEPLOY_MODE" == "1" ]]; then
    warn "For production: replace nginx/ssl/ certs with Let's Encrypt."
fi

warn "Edit backend/.env to set ALLOWED_ORIGINS and DRIFT_HOST."
echo ""
